# Generated by Django 4.0.4 on 2022-05-12 20:16

import core.models.base_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='tilt@ya.ru', max_length=127, unique=True)),
                ('phone', models.CharField(default='89999999999', max_length=15, unique=True)),
                ('first_name', models.CharField(default='Tilt', max_length=127, null=True)),
                ('last_name', models.CharField(default='Tilt', max_length=127, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(default='images/users/default.jpg', upload_to='images/users')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', core.models.base_user.BaseUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=127)),
                ('house', models.CharField(max_length=63)),
                ('appartement', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Businessman',
            fields=[
                ('businessman_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'businessman',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/categories/default.jpg', upload_to='images/categories')),
                ('category_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('monthly_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(default='images/companies/default.jpg', upload_to='images/companies')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('altitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/country/default.jpg', upload_to='images/country')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(primary_key=True, serialize=False)),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.businessman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addresses', models.ManyToManyField(to='core.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.address')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.courier')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'db_table': 'foodorder',
            },
        ),
        migrations.CreateModel(
            name='GoodInstance',
            fields=[
                ('good_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'goodinstance',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/markets/default.jpg', upload_to='images/markets')),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('market_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/market-types/default.jpg', upload_to='images/market-types')),
            ],
            options={
                'db_table': 'markettype',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('food_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foodorder')),
                ('good_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.goodinstance')),
            ],
            options={
                'db_table': 'order_data',
            },
        ),
        migrations.CreateModel(
            name='MarketInstance',
            fields=[
                ('market_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.address')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market')),
            ],
            options={
                'db_table': 'marketinstance',
            },
        ),
        migrations.AddField(
            model_name='market',
            name='market_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.markettype'),
        ),
        migrations.CreateModel(
            name='GoodServing',
            fields=[
                ('good_serving_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('caption', models.CharField(max_length=32)),
                ('good_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.goodinstance')),
            ],
            options={
                'db_table': 'goodserving',
            },
        ),
        migrations.AddField(
            model_name='goodinstance',
            name='market_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketinstance'),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('img', models.ImageField(default='images/goods/default.jpg', upload_to='images/goods')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marketinstance')),
            ],
            options={
                'db_table': 'good',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('altitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(default='images/city/default.jpg', upload_to='images/city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.AddField(
            model_name='businessman',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.market'),
        ),
        migrations.AddField(
            model_name='businessman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
    ]
