# Generated by Django 4.0.4 on 2022-05-15 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodorder_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=64)),
                ('bank_description', models.TextField()),
                ('bank_icon', models.ImageField(default='images/banks/default.png', upload_to='images/banks/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('client_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('company_img', models.ImageField(default='images/companies/default.jpg', upload_to='')),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='(?:(^[а-яА-Я]+)\\,?)\\s*(?:(?:г\\.?\\s*)([а-яА-Я]+)\\,?)\\s*(?:(?:ул)\\.?\\s*((?:[а-яА-Я]|\\s)+)\\,?)\\s*(?:(?:д)\\.?\\s*([а-яА-Я0-9]+)\\,?)\\s*(?:(?:кв|к)\\.?\\s*([а-яА-Я0-9]+))?$')])),
                ('employees_count', models.PositiveIntegerField()),
                ('employee_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('account_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{20}$')])),
                ('TIN_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('corr_account_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{20}$')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{20}$')])),
                ('TIN_num', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('corr_account_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d{20}$')])),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bank')),
            ],
        ),
    ]
