# Generated by Django 4.0.4 on 2022-05-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_company_description_clientrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
        migrations.AlterModelTable(
            name='clientrequest',
            table='clientrequest',
        ),
        migrations.AlterModelTable(
            name='marketrequest',
            table='marketrequest',
        ),
    ]
