# Generated by Django 4.0.4 on 2022-05-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_account_table_alter_bank_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='img',
            field=models.ImageField(default='images/requests/default.jpg', upload_to='images/requests/'),
        ),
        migrations.AlterField(
            model_name='marketrequest',
            name='img',
            field=models.ImageField(default='images/requests/default.jpg', upload_to='images/requests/'),
        ),
    ]
