# Generated by Django 4.0.4 on 2022-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_good_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodserving',
            name='price',
            field=models.DecimalField(decimal_places=2, default=650, max_digits=8),
            preserve_default=False,
        ),
    ]
